
/*Bibliotecas necesarias*/
package proyectoconexionpj;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.table.TableModel;


public class Restaurante extends javax.swing.JFrame {
    Connection conexion;
    String pass="postgres";
    String user="postgres";
    String idSeleccionado;
    DefaultTableModel modeloPlatillo = new DefaultTableModel(); 
    DefaultTableModel modeloSucursal = new DefaultTableModel(); 
    /**
     * Creates new form Restaurante
     */
    public Restaurante() {
        initComponents();
        estableceConexion();
        modeloTabla(1);
        llenaTabla(1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneSucusal = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        JBInsertarPlatillo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTPlatillo = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        JTNombrePlatillo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        JTDescripcionPlatillo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        JTCostoPlatillo = new javax.swing.JTextField();
        JBEliminarPlatillo = new javax.swing.JButton();
        JBModificarPlatillo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTSucursal = new javax.swing.JTable();
        JBModificarSucursal = new javax.swing.JButton();
        JBEliminarSucursal = new javax.swing.JButton();
        JBInsertarSucursal = new javax.swing.JButton();
        JTNombreSucursal = new javax.swing.JTextField();
        JTDireccionSucursal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPaneSucusal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPaneSucusalMouseClicked(evt);
            }
        });

        JBInsertarPlatillo.setText("Insertar");
        JBInsertarPlatillo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBInsertarPlatilloMouseClicked(evt);
            }
        });

        JTPlatillo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        JTPlatillo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTPlatilloMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTPlatillo);

        jLabel1.setText("Nombre");

        jLabel2.setText("Descripción");

        jLabel3.setText("Costo");

        JBEliminarPlatillo.setText("Eliminar");
        JBEliminarPlatillo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBEliminarPlatilloMouseClicked(evt);
            }
        });

        JBModificarPlatillo.setText("Modificar");
        JBModificarPlatillo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBModificarPlatilloMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 757, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JTNombrePlatillo, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(JTDescripcionPlatillo)
                            .addComponent(JTCostoPlatillo))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JBInsertarPlatillo)
                            .addComponent(JBEliminarPlatillo)
                            .addComponent(JBModificarPlatillo))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JTNombrePlatillo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBInsertarPlatillo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JTDescripcionPlatillo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBEliminarPlatillo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JTCostoPlatillo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBModificarPlatillo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPaneSucusal.addTab("Platillo", jPanel1);

        JTSucursal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        JTSucursal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTSucursalMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(JTSucursal);

        JBModificarSucursal.setText("Modificar");
        JBModificarSucursal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBModificarSucursalMouseClicked(evt);
            }
        });

        JBEliminarSucursal.setText("Eliminar");
        JBEliminarSucursal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBEliminarSucursalMouseClicked(evt);
            }
        });

        JBInsertarSucursal.setText("Insertar");
        JBInsertarSucursal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBInsertarSucursalMouseClicked(evt);
            }
        });

        jLabel5.setText("Dirección");

        jLabel6.setText("Nombre");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 757, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JTNombreSucursal, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(JTDireccionSucursal))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JBInsertarSucursal)
                            .addComponent(JBEliminarSucursal)
                            .addComponent(JBModificarSucursal))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(JTNombreSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBInsertarSucursal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(JTDireccionSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBEliminarSucursal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBModificarSucursal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPaneSucusal.addTab("Sucursal", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPaneSucusal)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPaneSucusal)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTPlatilloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTPlatilloMouseClicked
        int index = JTPlatillo.getSelectedRow();
        TableModel model = JTPlatillo.getModel();
        
        idSeleccionado =model.getValueAt(index, 0).toString();
        JTNombrePlatillo.setText(model.getValueAt(index, 1).toString());
        JTDescripcionPlatillo.setText(model.getValueAt(index, 2).toString());
        JTCostoPlatillo.setText(model.getValueAt(index, 3).toString());
    }//GEN-LAST:event_JTPlatilloMouseClicked

    private void JBInsertarPlatilloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBInsertarPlatilloMouseClicked
        try{
            Statement st = conexion.createStatement();
            String sql = "INSERT INTO RESTAURANTBD.Platillo(nombre,descripcion,costo)"
                    + "VALUES('" + JTNombrePlatillo.getText()+ "','" + 
                    JTDescripcionPlatillo.getText() + "','" + JTCostoPlatillo.getText() + "')";
            st.executeUpdate(sql);
            st.close();
            llenaTabla(1);            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Error al insertar " + e);
        }
    }//GEN-LAST:event_JBInsertarPlatilloMouseClicked

    private void JBEliminarPlatilloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBEliminarPlatilloMouseClicked
        try{
            Statement st = conexion.createStatement();
            String sql = "DELETE FROM RESTAURANTBD.Platillo "
                    + "WHERE idPlatillo=" + idSeleccionado;
            st.executeUpdate(sql);
            st.close();
            llenaTabla(1);            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Error al eliminar " + e);
        }
    }//GEN-LAST:event_JBEliminarPlatilloMouseClicked

    private void JBModificarPlatilloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBModificarPlatilloMouseClicked
        try{
            Statement st = conexion.createStatement();
            String sql = "UPDATE RESTAURANTBD.Platillo SET " + "nombre='" 
                    + JTNombrePlatillo.getText() + "',descripcion='"+JTDescripcionPlatillo.getText() 
                    + "',costo='" + JTCostoPlatillo.getText() + "'"
                    + "WHERE idPlatillo=" + idSeleccionado;
            st.executeUpdate(sql);
            st.close();
            llenaTabla(1);            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Error al eliminar " + e);
        }
    }//GEN-LAST:event_JBModificarPlatilloMouseClicked

    private void JTSucursalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTSucursalMouseClicked
        int index = JTSucursal.getSelectedRow();
        TableModel model = JTSucursal.getModel();
        
        idSeleccionado =model.getValueAt(index, 0).toString();
        JTNombreSucursal.setText(model.getValueAt(index, 1).toString());
        JTDireccionSucursal.setText(model.getValueAt(index, 2).toString());
    }//GEN-LAST:event_JTSucursalMouseClicked

    private void JBModificarSucursalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBModificarSucursalMouseClicked
        try{
            Statement st = conexion.createStatement();
            String sql = "UPDATE RESTAURANTBD.Sucursal SET " + "nombre='" 
                    + JTNombreSucursal.getText() + "',direccion='"+JTDireccionSucursal.getText() + "'"
                    + "WHERE idSucursal=" + idSeleccionado;
            st.executeUpdate(sql);
            st.close();
            llenaTabla(2);            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Error al eliminar " + e);
        }
    }//GEN-LAST:event_JBModificarSucursalMouseClicked

    private void JBEliminarSucursalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBEliminarSucursalMouseClicked
        try{
            Statement st = conexion.createStatement();
            String sql = "DELETE FROM RESTAURANTBD.Sucursal "
                    + "WHERE idSucursal=" + idSeleccionado;
            st.executeUpdate(sql);
            st.close();
            llenaTabla(2);            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Error al eliminar " + e);
        }
    }//GEN-LAST:event_JBEliminarSucursalMouseClicked

    private void JBInsertarSucursalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBInsertarSucursalMouseClicked
        try{
            Statement st = conexion.createStatement();
            String sql = "INSERT INTO RESTAURANTBD.Sucursal(nombre,direccion)"
                    + "VALUES('" + JTNombreSucursal.getText()+ "','" + 
                    JTDireccionSucursal.getText() + "')";
            st.executeUpdate(sql);
            st.close();
            llenaTabla(2);            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Error al insertar " + e);
        }
    }//GEN-LAST:event_JBInsertarSucursalMouseClicked

    private void jTabbedPaneSucusalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPaneSucusalMouseClicked
        llenaTabla(0);  
    }//GEN-LAST:event_jTabbedPaneSucusalMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Restaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Restaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Restaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Restaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Restaurante().setVisible(true);
            }
        });
    }
    
    private void estableceConexion() {
        try
        {
            conexion = DriverManager.getConnection(
                    "jdbc:postgresql://localhost:5432/restaurantedb", user, pass);
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Error al conectar" + ex);
        }                
    }
    
    private void modeloTabla(int tablaCargar) { 
        modeloPlatillo.addColumn("Id Platillo");
        modeloPlatillo.addColumn("Nombre");
        modeloPlatillo.addColumn("Descripción");
        modeloPlatillo.addColumn("Costo");
        JTPlatillo.setModel(modeloPlatillo);  
        
        modeloSucursal.addColumn("Id Platillo");
        modeloSucursal.addColumn("Nombre");
        modeloSucursal.addColumn("Dirección");
        JTSucursal.setModel(modeloSucursal);
    }

    private void llenaTabla(int tablaCargar) {
        switch(tablaCargar)
        {
            case 1:
                JTNombrePlatillo.setText("");
                JTDescripcionPlatillo.setText("");
                JTCostoPlatillo.setText("");

                modeloPlatillo.setRowCount(0);
                String datos1[] = new String[4];

                try{
                    Statement at = conexion.createStatement();
                    ResultSet rs =at.executeQuery("SELECT *FROM RESTAURANTBD.Platillo");
                    while(rs.next())
                    {
                        datos1[0] = rs.getString("idPlatillo");
                        datos1[1] = rs.getString("nombre");
                        datos1[2] = rs.getString("descripcion");
                        datos1[3] = rs.getString("costo");
                        modeloPlatillo.addRow(datos1);
                    }
                    rs.close();
                    at.close();
                }catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null,
                            "No se pudo actualizar la información");
                }
                break;
            case 2:
                JTNombreSucursal.setText("");
                JTDireccionSucursal.setText("");

                modeloSucursal.setRowCount(0);
                String datos2[] = new String[3];

                try{
                    Statement at = conexion.createStatement();
                    ResultSet rs =at.executeQuery("SELECT *FROM RESTAURANTBD.Sucursal");
                    while(rs.next())
                    {
                        datos2[0] = rs.getString("idSucursal");
                        datos2[1] = rs.getString("nombre");
                        datos2[2] = rs.getString("direccion");
                        modeloSucursal.addRow(datos2);
                    }
                    rs.close();
                    at.close();
                }catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null,
                            "No se pudo actualizar la información");
                }
                break;
            case 0:
                JTNombrePlatillo.setText("");
                JTDescripcionPlatillo.setText("");
                JTCostoPlatillo.setText("");

                modeloPlatillo.setRowCount(0);
                String datos11[] = new String[4];

                try{
                    Statement at = conexion.createStatement();
                    ResultSet rs =at.executeQuery("SELECT *FROM RESTAURANTBD.Platillo");
                    while(rs.next())
                    {
                        datos11[0] = rs.getString("idPlatillo");
                        datos11[1] = rs.getString("nombre");
                        datos11[2] = rs.getString("descripcion");
                        datos11[3] = rs.getString("costo");
                        modeloPlatillo.addRow(datos11);
                    }
                    rs.close();
                    at.close();
                }catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null,
                            "No se pudo actualizar la información");
                }
                
                JTNombreSucursal.setText("");
                JTDireccionSucursal.setText("");

                modeloSucursal.setRowCount(0);
                String datos22[] = new String[3];

                try{
                    Statement at = conexion.createStatement();
                    ResultSet rs =at.executeQuery("SELECT *FROM RESTAURANTBD.Sucursal");
                    while(rs.next())
                    {
                        datos22[0] = rs.getString("idSucursal");
                        datos22[1] = rs.getString("nombre");
                        datos22[2] = rs.getString("direccion");
                        modeloSucursal.addRow(datos22);
                    }
                    rs.close();
                    at.close();
                }catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null,
                            "No se pudo actualizar la información");
                }
                break;
        }        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBEliminarPlatillo;
    private javax.swing.JButton JBEliminarSucursal;
    private javax.swing.JButton JBInsertarPlatillo;
    private javax.swing.JButton JBInsertarSucursal;
    private javax.swing.JButton JBModificarPlatillo;
    private javax.swing.JButton JBModificarSucursal;
    private javax.swing.JTextField JTCostoPlatillo;
    private javax.swing.JTextField JTDescripcionPlatillo;
    private javax.swing.JTextField JTDireccionSucursal;
    private javax.swing.JTextField JTNombrePlatillo;
    private javax.swing.JTextField JTNombreSucursal;
    private javax.swing.JTable JTPlatillo;
    private javax.swing.JTable JTSucursal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPaneSucusal;
    // End of variables declaration//GEN-END:variables
}
